language: python
python:
  - "3.4"
  - "3.5"
virtualenv:
  system_site_packages: true
before_install:
  - SITE_PKG_DIR=$VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/site-packages
  - rm -f $VIRTUAL_ENV/lib/python$TRAVIS_PYTHON_VERSION/no-global-site-packages.txt
  - apt-get install python-numpy
  - apt-get install python-scipy
install:
  - pip install -r requirements.txt
script: nosetests test_functions.py
